
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_dev
  username: postgres
  password: 12345
test:
  <<: *default
  database: recipe_app_test
  username: postgres
  password: 12345
production:
  <<: *default
  database: recipe_app_pro
  username: postgres
  password: 12345
