default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 6991
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: recipe_app_dev

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: recipe_app_pro
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>